##################################################
## Deprecated and will be removed in the future ##
##################################################

Header header
geometry_msgs/Vector3 direction
geometry_msgs/Vector3 normal
geometry_msgs/Point palmpos
geometry_msgs/Vector3 ypr
int8 hands


# This changed to between true/false depending if there is a hand detected in the LMC frame
# bool is_present
